<a href="https://colab.research.google.com/github/amnazamir/Pomodoro-timer/blob/main/lab11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import seaborn as sns
import pandas as pd
import numpy as np

# Load built-in dataset
df = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset('titanic')
print(df.head())
print(df.info())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB
None

In [ ]:
df.describe(include='all')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
count,891.000000,891.000000,891,714.000000,891.000000,891.000000,891.000000,889,891,891,891,203,889,891,891
unique,NaN,NaN,2,NaN,NaN,NaN,NaN,3,3,3,2,7,3,2,2
top,NaN,NaN,male,NaN,NaN,NaN,NaN,S,Third,man,True,C,Southampton,no,True
freq,NaN,NaN,577,NaN,NaN,NaN,NaN,644,491,537,537,59,644,549,537
mean,0.383838,2.308642,NaN,29.699118,0.523008,0.381594,32.204208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.486592,0.836071,NaN,14.526497,1.102743,0.806057,49.693429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,0.000000,1.000000,NaN,0.420000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,0.000000,2.000000,NaN,20.125000,0.000000,0.000000,7.910400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,0.000000,3.000000,NaN,28.000000,0.000000,0.000000,14.454200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.000000,3.000000,NaN,38.000000,1.000000,0.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.000000,3.000000,NaN,80.000000,8.000000,6.000000,512.329200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset('titanic')
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:

df_drop = df.dropna(subset=['age'])
print(df_drop.shape)

(714, 15)

In [ ]:
df.fillna({'age': df['age'].mean()}, inplace=True)
print(df)

     survived  pclass     sex        age  sibsp  parch     fare embarked  \
0           0       3    male  22.000000      1      0   7.2500        S
1           1       1  female  38.000000      1      0  71.2833        C
2           1       3  female  26.000000      0      0   7.9250        S
3           1       1  female  35.000000      1      0  53.1000        S
4           0       3    male  35.000000      0      0   8.0500        S
..        ...     ...     ...        ...    ...    ...      ...      ...
886         0       2    male  27.000000      0      0  13.0000        S
887         1       1  female  19.000000      0      0  30.0000        S
888         0       3  female  29.699118      1      2  23.4500        S
889         1       1    male  26.000000      0      0  30.0000        C
890         0       3    male  32.000000      0      0   7.7500        Q

      class    who  adult_male deck  embark_town alive  alone
0     Third    man        True  NaN  Southampton    no  False
1     First  woman       False    C    Cherbourg   yes  False
2     Third  woman       False  NaN  Southampton   yes   True
3     First  woman       False    C  Southampton   yes  False
4     Third    man        True  NaN  Southampton    no   True
..      ...    ...         ...  ...          ...   ...    ...
886  Second    man        True  NaN  Southampton    no   True
887   First  woman       False    B  Southampton   yes   True
888   Third  woman       False  NaN  Southampton    no  False
889   First    man        True    C    Cherbourg   yes   True
890   Third    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]

In [ ]:
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])

print(df)

     survived  pclass     sex        age  sibsp  parch     fare embarked  \
0           0       3    male  22.000000      1      0   7.2500        S
1           1       1  female  38.000000      1      0  71.2833        C
2           1       3  female  26.000000      0      0   7.9250        S
3           1       1  female  35.000000      1      0  53.1000        S
4           0       3    male  35.000000      0      0   8.0500        S
..        ...     ...     ...        ...    ...    ...      ...      ...
886         0       2    male  27.000000      0      0  13.0000        S
887         1       1  female  19.000000      0      0  30.0000        S
888         0       3  female  29.699118      1      2  23.4500        S
889         1       1    male  26.000000      0      0  30.0000        C
890         0       3    male  32.000000      0      0   7.7500        Q

      class    who  adult_male deck  embark_town alive  alone
0     Third    man        True  NaN  Southampton    no  False
1     First  woman       False    C    Cherbourg   yes  False
2     Third  woman       False  NaN  Southampton   yes   True
3     First  woman       False    C  Southampton   yes  False
4     Third    man        True  NaN  Southampton    no   True
..      ...    ...         ...  ...          ...   ...    ...
886  Second    man        True  NaN  Southampton    no   True
887   First  woman       False    B  Southampton   yes   True
888   Third  woman       False  NaN  Southampton    no  False
889   First    man        True    C    Cherbourg   yes   True
890   Third    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]

In [ ]:
duplicates = df.duplicated().sum()
print("Duplicate rows:", duplicates)
df = df.drop_duplicates()

Duplicate rows: 107

In [ ]:
df.columns = df.columns.str.strip().str.lower()
print(df.columns)

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
df['name'] = df['who'].astype(str) + "_@#"
df['name'] = df['name'].str.replace('[^A-Za-z0-9 ]+', '', regex=True)
df['name'].head()

/tmp/ipykernel_9536/1795721642.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['name'] = df['who'].astype(str) + "_@#"
/tmp/ipykernel_9536/1795721642.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['name'] = df['name'].str.replace('[^A-Za-z0-9 ]+', '', regex=True)

0      man
1    woman
2    woman
3    woman
4      man
Name: name, dtype: object

In [ ]:
df.loc[:, 'embarked'] = df['embarked'].astype(str).str.strip()
print(df['embarked'].head())

0    S
1    C
2    S
3    S
4    S
Name: embarked, dtype: object

In [ ]:
df.loc[:, 'sex'] = df['sex'].str.capitalize()
print(df['sex'].head())

0      Male
1    Female
2    Female
3    Female
4      Male
Name: sex, dtype: object

In [ ]:
df.loc[:, 'pclass'] = df['pclass'].astype('category')
print(df['pclass'].head())

0    3
1    1
2    3
3    1
4    3
Name: pclass, dtype: category
Categories (3, int64): [1, 2, 3]

In [ ]:
Q1 = df['age'].quantile(0.25)
Q3 = df['age'].quantile(0.75)
IQR = Q3 - Q1
df = df[(df['age'] >= Q1 - 1.5*IQR) & (df['age'] <= Q3 + 1.5*IQR)]
print(df['age'].describe())

count    743.000000
mean      28.506873
std       11.664641
min        1.000000
25%       21.000000
50%       29.699118
75%       35.000000
max       56.000000
Name: age, dtype: float64

In [ ]:
invalid_fare = df[df['fare'] < 0]
print(invalid_fare)

Empty DataFrame
Columns: [survived, pclass, sex, age, sibsp, parch, fare, embarked, class, who, adult_male, deck, embark_town, alive, alone, name]
Index: []

In [ ]:
invalid_age = df[(df['age'] < 0) | (df['age'] > 100)]
print(invalid_age)

Empty DataFrame
Columns: [survived, pclass, sex, age, sibsp, parch, fare, embarked, class, who, adult_male, deck, embark_town, alive, alone, name]
Index: []

In [ ]:
def validate_dataset(df):
    print("Nulls:", df.isnull().sum().sum())
    print("Duplicates:", df.duplicated().sum())

    if 'age' in df.columns:
        print("Age range:", df['age'].min(), "-", df['age'].max())
    elif 'Age' in df.columns:
        print("Age range:", df['Age'].min(), "-", df['Age'].max())

validate_dataset(df)

Nulls: 869
Duplicates: 107
Age range: 0.42 - 80.0

In [ ]:
def clean_data(data):
    data = data.copy()

    data.columns = data.columns.str.strip().str.lower()

    data.drop_duplicates(inplace=True)

    data['age'] = data['age'].fillna(data['age'].mean())

    data['embarked'] = data['embarked'].fillna(
        data['embarked'].mode()[0]
    )

    data['sex'] = data['sex'].astype(str).str.capitalize()

    return data


df_clean = clean_data(df)

print(df_clean.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    Male  22.0      1      0   7.2500        S  Third
1         1       1  Female  38.0      1      0  71.2833        C  First
2         1       3  Female  26.0      0      0   7.9250        S  Third
3         1       1  Female  35.0      1      0  53.1000        S  First
4         0       3    Male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True

In [ ]:
df_clean.to_csv('cleaned_titanic.csv', index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [ ]:
import numpy as np

# Detect Outliers using IQR
Q1 = df_clean['fare'].quantile(0.25)
Q3 = df_clean['fare'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Mean of fare column
fare_mean = df_clean['fare'].mean()

# Replace outliers with mean
df_clean['fare'] = np.where(
    (df_clean['fare'] < lower_bound) |
    (df_clean['fare'] > upper_bound),
    fare_mean,
    df_clean['fare']
)

print("Outliers replaced successfully!")

Outliers replaced successfully!

In [ ]:
if df_clean.isnull().sum().sum() == 0 and df_clean.duplicated().sum() == 0:
    print("Data is clean!")
else:
    print("Dataset still contains nulls or duplicates.")

Dataset still contains nulls or duplicates.